name: Build and release Android APK

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '17'
      FLUTTER_VERSION: '3.24.5'
      AAB_PATH: build/app/outputs/bundle/release/app-release.aab
      KEYSTORE_PATH: android/upload-keystore.jks
      KEY_PROPS_PATH: android/key.properties
      LOCAL_PROPS_PATH: android/local.properties

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Prepare releases directory
        run: |
          mkdir releases
          
      - name: Verify version match
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"  # Remove 'v' prefix
          PUBSPEC_VERSION=$(cat pubspec.yaml | grep version | sed 's/version://' | xargs)
          if [ "$TAG_VERSION" != "$PUBSPEC_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) doesn't match pubspec.yaml version ($PUBSPEC_VERSION)"
            exit 1
          fi
          echo "Version check passed: $PUBSPEC_VERSION matches tag version"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Set Version Variables
        run: |
          VERSION=$(cat pubspec.yaml | grep version: | sed 's/version: //' | xargs)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          VERSION_CODE=$((MAJOR * 10000 + MINOR * 100 + PATCH))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "Version code will be: $VERSION_CODE"
          echo "Version name will be: $VERSION"

      # Decode our secrets
      - name: Decode Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > ${{ env.KEYSTORE_PATH }}

      - name: Decode Key Properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > ${{ env.KEY_PROPS_PATH }}

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK split per ABI
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dkotlin.incremental=false"
        run: flutter build apk --release --target-platform android-arm64,android-x64 --split-per-abi -- -Pversion_code=$VERSION_CODE -Pversion_name=$VERSION

      - name: Build APK universal
        run: flutter build apk --release -- -Pversion_code=$VERSION_CODE -Pversion_name=$VERSION
      
      - name: Copy to releases directory
        run: |
          cp ./build/app/outputs/flutter-apk/app-arm64-v8a-release.apk ./releases/syrius-mobile-${{ github.ref_name }}-arm64-v8a-release.apk
          cp ./build/app/outputs/flutter-apk/app-x86_64-release.apk ./releases/syrius-mobile-${{ github.ref_name }}-x86_64-release.apk
          cp ./build/app/outputs/flutter-apk/app-release.apk ./releases/syrius-mobile-${{ github.ref_name }}-universal-release.apk

      - name: Generate checksums
        run: |
          cd ./releases
          echo $(sha256sum *) >> SHA256CHECKSUMS.txt

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/*
          release_name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          file_glob: true
          overwrite: true

      - name: Build App Bundle
        run: flutter build appbundle --release -- -Pversion_code=$VERSION_CODE -Pversion_name=$VERSION

      - name: Setup Play Store Config
        run: |
          echo '${{ secrets.PLAY_STORE_CONFIG_JSON }}' > service-account.json

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service-account.json
          packageName: network.zenon.syrius.mobile
          releaseFiles: ${{ env.AAB_PATH }}
          track: internal
          status: completed